### ISSUE TITLE
Mobile ios browser crashes after account creation

### ISSUE THREAD

**Issue by Shaunwei** [ReByteAI/bug-tracker#1]
![image](https://github.com/ReByteAI/bug-tracker/assets/5101573/d4135085-84b1-4141-be9c-36a83b11377c)

![image](https://github.com/ReByteAI/bug-tracker/assets/5101573/185d78cf-c493-4727-8840-a969dff3baf2)

**Comment by wangfulong** [comment]
Banned the tour on the mobile phone
